OPENAI_API_KEY = "sk-WEKIObVihgmHZBd-UW5wsbTZDCi_OH219C70Zi1R7AT3BlbkFJEDKBe2Mcm0tOOyE_1Pe_xqWUX9oiX3sdeOnOGv18MA"
PINECONE_API_KEY = "7d4786c3-fc91-4605-b8e5-1f4807bcf148"
PINECONE_ENVIRONMENT = "us-east-1"
